# Generated by Django 3.0.8 on 2020-07-31 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Enabled', 'enabled'), ('Dissabled', 'Disabled')], max_length=9)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Enabled', 'enabled'), ('Dissabled', 'Disabled')], max_length=9)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Enabled', 'enabled'), ('Dissabled', 'Disabled')], max_length=9)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('uc', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Mandatory', 'Mandatory'), ('Elective', 'Elective')], max_length=9)),
                ('ht', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hl', models.DecimalField(decimal_places=2, max_digits=4)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.School')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Enabled', 'enabled'), ('Dissabled', 'Disabled')], max_length=9)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=9)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Person')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Section')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
