# Generated by Django 3.0.8 on 2020-08-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_enrollment_faculty_school_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='fecha_creacion',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='fecha_eliminacion',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='person',
            new_name='fk_person',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='section',
            new_name='fk_section',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='fecha_creacion',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='fecha_eliminacion',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='fecha_creacion',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='fecha_eliminacion',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='fecha_creacion',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='fecha_eliminacion',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='facultad',
            new_name='fk_facultad',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='fecha_creacion',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='fecha_eliminacion',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='school',
            new_name='fk_school',
        ),
    ]
